name: Build

on:
  push:
    branches: [master, test-actions]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config:
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            test: true
            cross: false
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            test: false
            cross: false
          - os: windows-latest
            target: i686-pc-windows-msvc
            test: true
            cross: false
          - os: macos-latest
            target: x86_64-apple-darwin
            test: true
            cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            test: false
            cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            test: true
            cross: false
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            test: true
            cross: false
    steps:
      - name: Git config
        if: ${{ matrix.config.os == 'windows-latest' }}
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install musl tools
        if: ${{ matrix.config.target == 'x86_64-unknown-linux-musl' }}
        run: sudo apt-get install musl-tools musl-dev
      - name: Install rust
        run: rustup update && rustup target add ${{ matrix.config.target }}
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-${{ matrix.config.target }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Install cross
        if: ${{ matrix.config.cross }}
        run: |
          type cross 2>&1 > /dev/null || cargo install --force cross
      - name: Build release all
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target ${{ matrix.config.target }} --features full
      - name: Build all
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} build --release --target ${{ matrix.config.target }} --features full
      - name: Test all
        if: ${{ matrix.config.test }}
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} test --release --target ${{ matrix.config.target }} --features full
      - name: Test gzip
        if: ${{ matrix.config.test }}
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} test --release --target ${{ matrix.config.target }} --no-default-features --features gzip
      - name: Test bgzip
        if: ${{ matrix.config.test }}
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} test --release --target ${{ matrix.config.target }} --no-default-features --features bgzip
      - name: Test bzip2
        if: ${{ matrix.config.test }}
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} test --release --target ${{ matrix.config.target }} --no-default-features --features bzip2
      - name: Test xz
        if: ${{ matrix.config.test }}
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} test --release --target ${{ matrix.config.target }} --no-default-features --features xz
      - name: Test zstd
        if: ${{ matrix.config.test }}
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} test --release --target ${{ matrix.config.target }} --no-default-features --features zstd
      - name: Test tokio and gzip
        if: ${{ matrix.config.test }}
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} test --release --target ${{ matrix.config.target }} --no-default-features --features tokio --features gzip
      - name: Test tokio_fs and gzip
        if: ${{ matrix.config.test }}
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} test --release --target ${{ matrix.config.target }} --no-default-features --features tokio_fs --features gzip
      - name: Test rayon and gzip
        if: ${{ matrix.config.test }}
        run: ${{ matrix.config.cross && 'cross' || 'cargo' }} test --release --target ${{ matrix.config.target }} --no-default-features --features rayon --features gzip
